services:
  web:
    environment:
      THESISTRACE_CADDY_HSTS_DIRECTIVE: 'header >Strict-Transport-Security "max-age=31536000"'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data

volumes:
  caddy-data:
