"""Legacy Strategy facade; the calculation implementation lives in Research Kernel."""

from thesistrace.research_kernel.strategy import (
    INITIAL_CASH,
    Position,
    StrategyCalculationError,
    account_weights,
    advance_strategy_metric_state,
    affordable_quantity,
    cagr,
    equal_weight_benchmark_return,
    execute_order,
    latest_adjusted_open_before,
    legal_order_quantity,
    mark_positions,
    market_rejection_reason,
    maximum_drawdown,
    money,
    run_strategy,
    split_child_orders,
    strategy_metrics,
    strategy_metrics_from_state,
    sum_position_values,
    transaction_cost,
    unique_events,
    weight_turnover,
)

__all__ = [
    "INITIAL_CASH",
    "Position",
    "StrategyCalculationError",
    "account_weights",
    "advance_strategy_metric_state",
    "affordable_quantity",
    "cagr",
    "equal_weight_benchmark_return",
    "execute_order",
    "latest_adjusted_open_before",
    "legal_order_quantity",
    "market_rejection_reason",
    "mark_positions",
    "maximum_drawdown",
    "money",
    "run_strategy",
    "split_child_orders",
    "strategy_metrics",
    "strategy_metrics_from_state",
    "sum_position_values",
    "transaction_cost",
    "unique_events",
    "weight_turnover",
]
