"""Index actual evidence per field; no inferred production qualification."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent
inventory = json.loads((root / 'dsl-field-inventory-226.json').read_text())['fields']
coverage = {x['source_column']: x for x in json.loads(
    (root / 'indicator-catalog-coverage.json').read_text())['fields']}
ratios = json.loads((root / 'indicator-ratio-scale-crosschecks.json').read_text())
semantics = json.loads((root / 'indicator-catalog-semantic-crosschecks.json').read_text())
primary = json.loads((root / 'indicator-primary-report-crosschecks.json').read_text())['facts']
pilot = {'eps', 'bps', 'current_ratio', 'roe', 'q_roe', 'netprofit_yoy'}
# Explicit offline qualification decisions; this is not a runtime registry.
decisions = {'adminexp_of_gr': ('percent',
                    'ratio',
                    'latest_visible_report_cumulative',
                    'supplier report cumulative: administrative expense / total revenue; '
                    'historical R&D classification retained',
                    'indicator-ratio-scale-crosschecks.json'),
 'ar_turn': ('multiple',
             'multiple',
             'latest_visible_report_cumulative',
             'supplier report cumulative: operating revenue / year-start and ending average '
             'receivables',
             'indicator-ratio-scale-crosschecks.json'),
 'arturn_days': ('day',
                 'day',
                 'latest_visible_report_cumulative',
                 'supplier report cumulative: receivable turnover days; report months times30 '
                 'divided by rounded turnover',
                 'indicator-ratio-scale-crosschecks.json'),
 'assets_to_eqt': ('multiple',
                   'multiple',
                   'latest_visible_report_end',
                   'supplier report end: total assets / consolidated equity',
                   'indicator-ratio-scale-crosschecks.json'),
 'assets_turn': ('multiple',
                 'multiple',
                 'latest_visible_report_cumulative',
                 'supplier report cumulative: total revenue / year-start and ending average total '
                 'assets',
                 'indicator-ratio-scale-crosschecks.json'),
 'assets_yoy': ('percent',
                'ratio',
                'latest_visible_report_year_start_growth',
                'supplier report year start growth: total assets compared with preceding year end',
                'indicator-ratio-scale-crosschecks.json'),
 'basic_eps_yoy': ('percent',
                   'ratio',
                   'latest_visible_report_yoy',
                   'supplier report yoy: basic EPS',
                   'indicator-ratio-scale-crosschecks.json'),
 'bps_yoy': ('percent',
             'ratio',
             'latest_visible_report_year_start_growth',
             'supplier report year start growth: book value per share compared with preceding year '
             'end',
             'indicator-ratio-scale-crosschecks.json'),
 'ca_to_assets': ('percent',
                  'ratio',
                  'latest_visible_report_end',
                  'supplier report end: current assets / total assets',
                  'indicator-ratio-scale-crosschecks.json'),
 'ca_turn': ('multiple',
             'multiple',
             'latest_visible_report_cumulative',
             'supplier report cumulative: total revenue / year-start and ending average current '
             'assets',
             'indicator-ratio-scale-crosschecks.json'),
 'capital_rese_ps': ('CNY/share',
                     'CNY/share',
                     'latest_visible_report_end',
                     'Supplier ending capital reserve per share.',
                     'indicator-ratio-scale-crosschecks.json'),
 'capitalized_to_da': ('ratio',
                       'ratio',
                       'latest_visible_report_cumulative',
                       'Supplier cumulative supplier capital expenditure / depreciation and '
                       'amortization.',
                       'indicator-ratio-scale-crosschecks.json'),
 'cash_ratio': ('multiple',
                'multiple',
                'latest_visible_report_end',
                'Supplier conservative quick ratio;12 matching period-end liquid-receivable '
                'comparisons anchor scale. Other component alternatives differ and do not define a '
                'universal reconstruction.',
                'indicator-ratio-scale-crosschecks.json'),
 'cash_to_liqdebt': ('ratio',
                     'ratio',
                     'latest_visible_report_end',
                     'supplier report end: monetary funds / current liabilities',
                     'indicator-ratio-scale-crosschecks.json'),
 'cash_to_liqdebt_withinterest': ('ratio',
                                  'ratio',
                                  'latest_visible_report_end',
                                  'supplier report end: monetary funds / interest-bearing current '
                                  'liabilities',
                                  'indicator-ratio-scale-crosschecks.json'),
 'cfps': ('CNY/share',
          'CNY/share',
          'latest_visible_report_cumulative',
          'Supplier cumulative net cashflow per ending share; not operating cashflow.',
          'indicator-ratio-scale-crosschecks.json'),
 'cfps_yoy': ('percent',
              'ratio',
              'latest_visible_report_yoy',
              'supplier report yoy: operating net cashflow per share; not total net cashflow per '
              'share',
              'indicator-ratio-scale-crosschecks.json'),
 'cogs_of_sales': ('percent',
                   'ratio',
                   'latest_visible_report_cumulative',
                   'supplier report cumulative: operating cost / operating revenue',
                   'indicator-ratio-scale-crosschecks.json'),
 'current_exint': ('CNY',
                   'CNY',
                   'latest_visible_report_end',
                   'supplier report end: non-interest current liabilities; supplier component '
                   'classification retained',
                   'indicator-ratio-scale-crosschecks.json'),
 'currentdebt_to_debt': ('percent',
                         'ratio',
                         'latest_visible_report_end',
                         'supplier report end: current liabilities / total liabilities',
                         'indicator-ratio-scale-crosschecks.json'),
 'daa': ('CNY',
         'CNY',
         'latest_visible_report_cumulative',
         'supplier report cumulative: depreciation and amortization',
         'indicator-ratio-scale-crosschecks.json'),
 'debt_to_assets': ('percent',
                    'ratio',
                    'latest_visible_report_end',
                    'supplier report end: total liabilities / total assets',
                    'indicator-ratio-scale-crosschecks.json'),
 'debt_to_eqt': ('multiple',
                 'multiple',
                 'latest_visible_report_end',
                 'supplier report end: total liabilities / consolidated equity',
                 'indicator-ratio-scale-crosschecks.json'),
 'diluted2_eps': ('CNY/share',
                  'CNY/share',
                  'latest_visible_report_cumulative',
                  'Supplier cumulative parent net profit per ending share; not diluted EPS.',
                  'indicator-ratio-scale-crosschecks.json'),
 'dp_assets_to_eqt': ('multiple',
                      'multiple',
                      'latest_visible_report_cumulative',
                      'supplier report cumulative: year-start and ending average assets / average '
                      'parent equity',
                      'indicator-ratio-scale-crosschecks.json'),
 'dt_eps': ('CNY/share',
            'CNY/share',
            'latest_visible_report_cumulative',
            'supplier report cumulative: diluted EPS; distinct from profit divided by ending '
            'shares',
            'indicator-ratio-scale-crosschecks.json'),
 'dt_eps_yoy': ('percent',
                'ratio',
                'latest_visible_report_yoy',
                'supplier report yoy: diluted EPS',
                'indicator-ratio-scale-crosschecks.json'),
 'dt_netprofit_yoy': ('percent',
                      'ratio',
                      'latest_visible_report_yoy',
                      'supplier report yoy: parent deducted net profit; retain supplier rounding '
                      'and adjustments',
                      'indicator-ratio-scale-crosschecks.json'),
 'dtprofit_to_profit': ('percent',
                        'ratio',
                        'latest_visible_report_cumulative',
                        'supplier report cumulative: deducted net profit / parent net income',
                        'indicator-ratio-scale-crosschecks.json'),
 'ebit': ('CNY',
          'CNY',
          'latest_visible_report_cumulative',
          'supplier report cumulative: earnings before interest and tax',
          'indicator-ratio-scale-crosschecks.json'),
 'ebit_of_gr': ('percent',
                'ratio',
                'latest_visible_report_cumulative',
                'supplier report cumulative: EBIT / total revenue',
                'indicator-ratio-scale-crosschecks.json'),
 'ebit_ps': ('CNY/share',
             'CNY/share',
             'latest_visible_report_cumulative',
             'Supplier cumulative supplier EBIT per ending share.',
             'indicator-ratio-scale-crosschecks.json'),
 'ebit_to_interest': ('multiple',
                      'multiple',
                      'latest_visible_report_cumulative',
                      'Cumulative EBIT divided by supplier interest scope; Vanke annual and '
                      'interim gross-interest-less-income denominator comparisons match '
                      'within0.0001. Capitalized interest is included in these samples.',
                      'indicator-primary-report-crosschecks.json'),
 'ebitda': ('CNY',
            'CNY',
            'latest_visible_report_cumulative',
            'supplier report cumulative: earnings before interest, tax, depreciation and '
            'amortization',
            'indicator-ratio-scale-crosschecks.json'),
 'ebitda_to_debt': ('ratio',
                    'ratio',
                    'latest_visible_report_cumulative',
                    'supplier report cumulative: cumulative EBITDA / ending total liabilities',
                    'indicator-ratio-scale-crosschecks.json'),
 'ebt_yoy': ('percent',
             'ratio',
             'latest_visible_report_yoy',
             'supplier report yoy: total profit',
             'indicator-ratio-scale-crosschecks.json'),
 'eqt_to_debt': ('ratio',
                 'ratio',
                 'latest_visible_report_end',
                 'supplier report end: parent equity / total liabilities',
                 'indicator-ratio-scale-crosschecks.json'),
 'eqt_to_interestdebt': ('ratio',
                         'ratio',
                         'latest_visible_report_end',
                         'supplier report end: parent equity / interest-bearing debt',
                         'indicator-ratio-scale-crosschecks.json'),
 'eqt_to_talcapital': ('percent',
                       'ratio',
                       'latest_visible_report_end',
                       'supplier report end: parent equity / invested capital',
                       'indicator-ratio-scale-crosschecks.json'),
 'eqt_yoy': ('percent',
             'ratio',
             'latest_visible_report_year_start_growth',
             'supplier report year start growth: parent equity compared with preceding year end',
             'indicator-ratio-scale-crosschecks.json'),
 'equity_yoy': ('percent',
                'ratio',
                'latest_visible_report_yoy',
                'supplier report yoy: supplier net assets; parent-equity sample has a historical '
                'adjustment discrepancy',
                'indicator-ratio-scale-crosschecks.json'),
 'expense_of_sales': ('percent',
                      'ratio',
                      'latest_visible_report_cumulative',
                      'supplier report cumulative: period expenses / operating revenue; historical '
                      'R&D classification retained',
                      'indicator-ratio-scale-crosschecks.json'),
 'extra_item': ('CNY',
                'CNY',
                'latest_visible_report_cumulative',
                'supplier report cumulative: nonrecurring profit or loss; retain supplier '
                'adjustment and rounding',
                'indicator-ratio-scale-crosschecks.json'),
 'fa_turn': ('multiple',
             'multiple',
             'latest_visible_report_cumulative',
             'supplier report cumulative: total revenue / year-start and ending average fixed '
             'assets',
             'indicator-ratio-scale-crosschecks.json'),
 'fcfe': ('CNY',
          'CNY',
          'latest_visible_report_cumulative',
          'Supplier equity free cashflow;13 matches to same-period firm cashflow plus '
          'borrowing/bond proceeds less repayments, across all quarter ends.',
          'indicator-free-cashflow-crosschecks.json'),
 'fcfe_ps': ('CNY/share',
             'CNY/share',
             'latest_visible_report_cumulative',
             'Supplier equity free cashflow per ending share;18 direct amount/share matches; flow '
             'period anchored in free-cashflow crosschecks.',
             'indicator-ratio-scale-crosschecks.json'),
 'fcff': ('CNY',
          'CNY',
          'latest_visible_report_cumulative',
          'Supplier firm free cashflow;31 cumulative statement free_cashflow matches across all '
          'quarter ends,2 retained historical differences.',
          'indicator-free-cashflow-crosschecks.json'),
 'fcff_ps': ('CNY/share',
             'CNY/share',
             'latest_visible_report_cumulative',
             'Supplier firm free cashflow per ending share;18 direct amount/share matches; flow '
             'period anchored in free-cashflow crosschecks.',
             'indicator-ratio-scale-crosschecks.json'),
 'finaexp_of_gr': ('percent',
                   'ratio',
                   'latest_visible_report_cumulative',
                   'supplier report cumulative: finance expense / total revenue',
                   'indicator-ratio-scale-crosschecks.json'),
 'fixed_assets': ('CNY',
                  'CNY',
                  'latest_visible_report_end',
                  'supplier report end: fixed-asset aggregate including construction and '
                  'investment property in samples',
                  'indicator-ratio-scale-crosschecks.json'),
 'gc_of_gr': ('percent',
              'ratio',
              'latest_visible_report_cumulative',
              'supplier report cumulative: total operating cost / total revenue',
              'indicator-ratio-scale-crosschecks.json'),
 'gross_margin': ('CNY',
                  'CNY',
                  'latest_visible_report_cumulative',
                  'Cumulative operating revenue less operating cost; authoring name gross_profit.',
                  'indicator-catalog-semantic-crosschecks.json'),
 'grossprofit_margin': ('percent',
                        'ratio',
                        'latest_visible_report_cumulative',
                        'supplier report cumulative: gross profit / operating revenue',
                        'indicator-ratio-scale-crosschecks.json'),
 'impai_ttm': ('percent',
               'ratio',
               'latest_visible_report_cumulative',
               'Cumulative impairment loss divided by total revenue; source name does not imply '
               'TTM.',
               'indicator-catalog-semantic-crosschecks.json'),
 'int_to_talcap': ('percent',
                   'ratio',
                   'latest_visible_report_end',
                   'supplier report end: interest-bearing debt / invested capital',
                   'indicator-ratio-scale-crosschecks.json'),
 'interestdebt': ('CNY',
                  'CNY',
                  'latest_visible_report_end',
                  'supplier report end: interest-bearing debt; total liabilities less supplier '
                  'non-interest liabilities',
                  'indicator-ratio-scale-crosschecks.json'),
 'interst_income': ('CNY',
                    'CNY',
                    'latest_visible_report_cumulative',
                    'supplier report cumulative: interest expense, despite source spelling '
                    'interst_income',
                    'indicator-ratio-scale-crosschecks.json'),
 'inv_turn': ('multiple',
              'multiple',
              'latest_visible_report_cumulative',
              'supplier report cumulative: operating cost / year-start and ending average '
              'inventory',
              'indicator-ratio-scale-crosschecks.json'),
 'invest_capital': ('CNY',
                    'CNY',
                    'latest_visible_report_end',
                    'supplier report end: consolidated equity plus interest-bearing debt',
                    'indicator-ratio-scale-crosschecks.json'),
 'investincome_of_ebt': ('percent',
                         'ratio',
                         'latest_visible_report_cumulative',
                         'supplier report cumulative: value-change net income / total profit; not '
                         'investment income alone',
                         'indicator-ratio-scale-crosschecks.json'),
 'invturn_days': ('day',
                  'day',
                  'latest_visible_report_cumulative',
                  'supplier report cumulative: inventory turnover days; report months times30 '
                  'divided by rounded turnover',
                  'indicator-ratio-scale-crosschecks.json'),
 'longdeb_to_debt': ('percent',
                     'ratio',
                     'latest_visible_report_end',
                     'supplier report end: noncurrent liabilities / total liabilities',
                     'indicator-ratio-scale-crosschecks.json'),
 'longdebt_to_workingcapital': ('ratio',
                                'ratio',
                                'latest_visible_report_end',
                                'supplier report end: long-term debt / working capital; supplier '
                                'debt classification retained',
                                'indicator-ratio-scale-crosschecks.json'),
 'n_op_profit_of_ebt': ('percent',
                        'ratio',
                        'latest_visible_report_cumulative',
                        'supplier report cumulative: nonoperating receipts less expenses / total '
                        'profit',
                        'indicator-ratio-scale-crosschecks.json'),
 'nca_to_assets': ('percent',
                   'ratio',
                   'latest_visible_report_end',
                   'supplier report end: noncurrent assets / total assets',
                   'indicator-ratio-scale-crosschecks.json'),
 'netdebt': ('CNY',
             'CNY',
             'latest_visible_report_end',
             'supplier report end: interest-bearing debt less monetary funds',
             'indicator-ratio-scale-crosschecks.json'),
 'netprofit_margin': ('percent',
                      'ratio',
                      'latest_visible_report_cumulative',
                      'supplier report cumulative: consolidated net income / operating revenue',
                      'indicator-ratio-scale-crosschecks.json'),
 'networking_capital': ('CNY',
                        'CNY',
                        'latest_visible_report_end',
                        'supplier report end: current assets less monetary funds and non-interest '
                        'current liabilities',
                        'indicator-ratio-scale-crosschecks.json'),
 'non_op_profit': ('CNY',
                   'CNY',
                   'latest_visible_report_cumulative',
                   'supplier report cumulative: nonoperating net profit; not gross nonoperating '
                   'receipts',
                   'indicator-ratio-scale-crosschecks.json'),
 'noncurrent_exint': ('CNY',
                      'CNY',
                      'latest_visible_report_end',
                      'supplier report end: non-interest noncurrent liabilities; supplier '
                      'component classification retained',
                      'indicator-ratio-scale-crosschecks.json'),
 'nop_to_ebt': ('percent',
                'ratio',
                'latest_visible_report_cumulative',
                'supplier report cumulative: supplier nonoperating net profit / total profit',
                'indicator-ratio-scale-crosschecks.json'),
 'npta': ('percent',
          'ratio',
          'latest_visible_report_cumulative',
          'supplier report cumulative: consolidated net profit / year-start and ending average '
          'total assets',
          'indicator-ratio-scale-crosschecks.json'),
 'ocf_to_debt': ('ratio',
                 'ratio',
                 'latest_visible_report_cumulative',
                 'supplier report cumulative: cumulative operating net cashflow / ending total '
                 'liabilities',
                 'indicator-ratio-scale-crosschecks.json'),
 'ocf_to_interestdebt': ('ratio',
                         'ratio',
                         'latest_visible_report_cumulative',
                         'supplier report cumulative: cumulative operating net cashflow / ending '
                         'interest-bearing debt',
                         'indicator-ratio-scale-crosschecks.json'),
 'ocf_to_netdebt': ('ratio',
                    'ratio',
                    'latest_visible_report_cumulative',
                    'supplier report cumulative: cumulative operating net cashflow / ending net '
                    'debt',
                    'indicator-ratio-scale-crosschecks.json'),
 'ocf_to_opincome': ('ratio',
                     'ratio',
                     'latest_visible_report_cumulative',
                     'Supplier cumulative operating net cashflow / operating activity net income.',
                     'indicator-ratio-scale-crosschecks.json'),
 'ocf_to_or': ('ratio',
               'ratio',
               'latest_visible_report_cumulative',
               'Supplier cumulative operating net cashflow / operating revenue.',
               'indicator-ratio-scale-crosschecks.json'),
 'ocf_to_profit': ('percent',
                   'ratio',
                   'latest_visible_report_cumulative',
                   'Supplier cumulative operating net cashflow / operating profit.',
                   'indicator-ratio-scale-crosschecks.json'),
 'ocf_to_shortdebt': ('ratio',
                      'ratio',
                      'latest_visible_report_cumulative',
                      'supplier report cumulative: cumulative operating net cashflow / ending '
                      'current liabilities',
                      'indicator-ratio-scale-crosschecks.json'),
 'ocf_yoy': ('percent',
             'ratio',
             'latest_visible_report_yoy',
             'supplier report yoy: operating net cashflow',
             'indicator-ratio-scale-crosschecks.json'),
 'ocfps': ('CNY/share',
           'CNY/share',
           'latest_visible_report_cumulative',
           'Supplier cumulative operating net cashflow per ending share.',
           'indicator-ratio-scale-crosschecks.json'),
 'op_income': ('CNY',
               'CNY',
               'latest_visible_report_cumulative',
               'supplier report cumulative: operating activity net income; not operating profit or '
               'net cashflow',
               'indicator-ratio-scale-crosschecks.json'),
 'op_of_gr': ('percent',
              'ratio',
              'latest_visible_report_cumulative',
              'supplier report cumulative: operating profit / total revenue',
              'indicator-ratio-scale-crosschecks.json'),
 'op_to_debt': ('ratio',
                'ratio',
                'latest_visible_report_cumulative',
                'supplier report cumulative: cumulative operating profit / ending total '
                'liabilities',
                'indicator-ratio-scale-crosschecks.json'),
 'op_to_ebt': ('percent',
               'ratio',
               'latest_visible_report_cumulative',
               'supplier report cumulative: operating profit / total profit',
               'indicator-ratio-scale-crosschecks.json'),
 'op_to_liqdebt': ('ratio',
                   'ratio',
                   'latest_visible_report_cumulative',
                   'supplier report cumulative: cumulative operating profit / ending current '
                   'liabilities',
                   'indicator-ratio-scale-crosschecks.json'),
 'op_yoy': ('percent',
            'ratio',
            'latest_visible_report_yoy',
            'supplier report yoy: operating profit',
            'indicator-ratio-scale-crosschecks.json'),
 'opincome_of_ebt': ('percent',
                     'ratio',
                     'latest_visible_report_cumulative',
                     'supplier report cumulative: operating activity net income / total profit',
                     'indicator-ratio-scale-crosschecks.json'),
 'or_yoy': ('percent',
            'ratio',
            'latest_visible_report_yoy',
            'supplier report yoy: operating revenue',
            'indicator-ratio-scale-crosschecks.json'),
 'profit_dedt': ('CNY',
                 'CNY',
                 'latest_visible_report_cumulative',
                 'supplier report cumulative: deducted net profit; retain supplier definition and '
                 'adjustments',
                 'indicator-ratio-scale-crosschecks.json'),
 'profit_prefin_exp': ('CNY',
                       'CNY',
                       'latest_visible_report_cumulative',
                       'supplier report cumulative: operating profit before finance expense',
                       'indicator-ratio-scale-crosschecks.json'),
 'profit_to_gr': ('percent',
                  'ratio',
                  'latest_visible_report_cumulative',
                  'supplier report cumulative: consolidated net income / total revenue',
                  'indicator-ratio-scale-crosschecks.json'),
 'profit_to_op': ('percent',
                  'ratio',
                  'latest_visible_report_cumulative',
                  'supplier report cumulative: total profit / total revenue in retained samples; '
                  'supplier label says revenue',
                  'indicator-ratio-scale-crosschecks.json'),
 'q_adminexp_to_gr': ('percent',
                      'ratio',
                      'latest_visible_single_quarter',
                      'supplier single quarter: administrative expense / total revenue; historical '
                      'expense classification retained',
                      'indicator-ratio-scale-crosschecks.json'),
 'q_dt_roe': ('percent',
              'ratio',
              'latest_visible_single_quarter',
              'supplier single quarter: single-quarter deducted net profit / previous-quarter and '
              'ending average parent equity',
              'indicator-ratio-scale-crosschecks.json'),
 'q_dtprofit': ('CNY',
                'CNY',
                'latest_visible_single_quarter',
                'supplier single quarter: single-quarter deducted net profit; supplier adjustments '
                'retained',
                'indicator-ratio-scale-crosschecks.json'),
 'q_dtprofit_to_profit': ('percent',
                          'ratio',
                          'latest_visible_single_quarter',
                          'supplier single quarter: deducted net profit / parent net income',
                          'indicator-ratio-scale-crosschecks.json'),
 'q_eps': ('CNY/share',
           'CNY/share',
           'latest_visible_single_quarter',
           'Supplier supplier single-quarter earnings per share.',
           'indicator-ratio-scale-crosschecks.json'),
 'q_exp_to_sales': ('percent',
                    'ratio',
                    'latest_visible_single_quarter',
                    'supplier single quarter: period expenses / operating revenue; historical '
                    'expense classification retained',
                    'indicator-ratio-scale-crosschecks.json'),
 'q_finaexp_to_gr': ('percent',
                     'ratio',
                     'latest_visible_single_quarter',
                     'supplier single quarter: finance expense / total revenue',
                     'indicator-ratio-scale-crosschecks.json'),
 'q_gc_to_gr': ('percent',
                'ratio',
                'latest_visible_single_quarter',
                'supplier single quarter: total operating cost / total revenue',
                'indicator-ratio-scale-crosschecks.json'),
 'q_gr_qoq': ('percent',
              'ratio',
              'latest_visible_single_quarter_qoq',
              'supplier single quarter qoq: single-quarter total revenue versus preceding quarter',
              'indicator-ratio-scale-crosschecks.json'),
 'q_gr_yoy': ('percent',
              'ratio',
              'latest_visible_single_quarter_yoy',
              'supplier single quarter yoy: single-quarter total revenue versus same quarter last '
              'year',
              'indicator-ratio-scale-crosschecks.json'),
 'q_gsprofit_margin': ('percent',
                       'ratio',
                       'latest_visible_single_quarter',
                       'supplier single quarter: gross profit / operating revenue',
                       'indicator-ratio-scale-crosschecks.json'),
 'q_impair_to_gr_ttm': ('percent',
                        'ratio',
                        'latest_visible_single_quarter',
                        'Single-quarter impairment loss divided by single-quarter total revenue.',
                        'indicator-catalog-semantic-crosschecks.json'),
 'q_investincome': ('CNY',
                    'CNY',
                    'latest_visible_single_quarter',
                    'supplier single quarter: single-quarter value-change net income',
                    'indicator-ratio-scale-crosschecks.json'),
 'q_investincome_to_ebt': ('percent',
                           'ratio',
                           'latest_visible_single_quarter',
                           'supplier single quarter: value-change net income / total profit',
                           'indicator-ratio-scale-crosschecks.json'),
 'q_netprofit_margin': ('percent',
                        'ratio',
                        'latest_visible_single_quarter',
                        'supplier single quarter: consolidated net income / operating revenue',
                        'indicator-ratio-scale-crosschecks.json'),
 'q_netprofit_qoq': ('percent',
                     'ratio',
                     'latest_visible_single_quarter_qoq',
                     'supplier single quarter qoq: single-quarter parent net profit versus '
                     'preceding quarter',
                     'indicator-ratio-scale-crosschecks.json'),
 'q_netprofit_yoy': ('percent',
                     'ratio',
                     'latest_visible_single_quarter_yoy',
                     'supplier single quarter yoy: single-quarter parent net profit versus same '
                     'quarter last year',
                     'indicator-ratio-scale-crosschecks.json'),
 'q_npta': ('percent',
            'ratio',
            'latest_visible_single_quarter',
            'supplier single quarter: single-quarter consolidated net profit / previous-quarter '
            'and ending average assets',
            'indicator-ratio-scale-crosschecks.json'),
 'q_ocf_to_or': ('percent',
                 'ratio',
                 'latest_visible_single_quarter',
                 'Supplier single-quarter operating net cashflow / operating activity net income.',
                 'indicator-ratio-scale-crosschecks.json'),
 'q_ocf_to_sales': ('percent',
                    'ratio',
                    'latest_visible_single_quarter',
                    'Supplier single-quarter operating net cashflow / operating revenue.',
                    'indicator-ratio-scale-crosschecks.json'),
 'q_op_qoq': ('percent',
              'ratio',
              'latest_visible_single_quarter_qoq',
              'supplier single quarter qoq: single-quarter operating profit versus preceding '
              'quarter',
              'indicator-ratio-scale-crosschecks.json'),
 'q_op_to_gr': ('percent',
                'ratio',
                'latest_visible_single_quarter',
                'supplier single quarter: operating profit / total revenue',
                'indicator-ratio-scale-crosschecks.json'),
 'q_op_yoy': ('percent',
              'ratio',
              'latest_visible_single_quarter_yoy',
              'supplier single quarter yoy: single-quarter operating profit versus same quarter '
              'last year',
              'indicator-ratio-scale-crosschecks.json'),
 'q_opincome': ('CNY',
                'CNY',
                'latest_visible_single_quarter',
                'supplier single quarter: single-quarter operating activity net income',
                'indicator-ratio-scale-crosschecks.json'),
 'q_opincome_to_ebt': ('percent',
                       'ratio',
                       'latest_visible_single_quarter',
                       'supplier single quarter: operating activity net income / total profit',
                       'indicator-ratio-scale-crosschecks.json'),
 'q_profit_qoq': ('percent',
                  'ratio',
                  'latest_visible_single_quarter_qoq',
                  'supplier single quarter qoq: single-quarter consolidated net profit versus '
                  'preceding quarter',
                  'indicator-ratio-scale-crosschecks.json'),
 'q_profit_to_gr': ('percent',
                    'ratio',
                    'latest_visible_single_quarter',
                    'supplier single quarter: consolidated net income / total revenue',
                    'indicator-ratio-scale-crosschecks.json'),
 'q_profit_yoy': ('percent',
                  'ratio',
                  'latest_visible_single_quarter_yoy',
                  'supplier single quarter yoy: single-quarter consolidated net profit versus same '
                  'quarter last year',
                  'indicator-ratio-scale-crosschecks.json'),
 'q_saleexp_to_gr': ('percent',
                     'ratio',
                     'latest_visible_single_quarter',
                     'supplier single quarter: selling expense / total revenue',
                     'indicator-ratio-scale-crosschecks.json'),
 'q_sales_qoq': ('percent',
                 'ratio',
                 'latest_visible_single_quarter_qoq',
                 'supplier single quarter qoq: single-quarter operating revenue versus preceding '
                 'quarter',
                 'indicator-ratio-scale-crosschecks.json'),
 'q_sales_yoy': ('percent',
                 'ratio',
                 'latest_visible_single_quarter_yoy',
                 'supplier single quarter yoy: single-quarter operating revenue versus same '
                 'quarter last year',
                 'indicator-ratio-scale-crosschecks.json'),
 'q_salescash_to_or': ('percent',
                       'ratio',
                       'latest_visible_single_quarter',
                       'Supplier single-quarter sales and service cash receipts / operating '
                       'revenue.',
                       'indicator-ratio-scale-crosschecks.json'),
 'quick_ratio': ('multiple',
                 'multiple',
                 'latest_visible_report_end',
                 'supplier report end: current assets less inventory / current liabilities',
                 'indicator-ratio-scale-crosschecks.json'),
 'rd_exp': ('CNY',
            'CNY',
            'latest_visible_report_cumulative',
            'Total research investment including expensed and capitalized amounts.',
            'indicator-primary-report-crosschecks.json'),
 'retained_earnings': ('CNY',
                       'CNY',
                       'latest_visible_report_end',
                       'supplier report end: surplus reserve plus undistributed profit',
                       'indicator-ratio-scale-crosschecks.json'),
 'retainedps': ('CNY/share',
                'CNY/share',
                'latest_visible_report_end',
                'Supplier ending retained earnings per share.',
                'indicator-ratio-scale-crosschecks.json'),
 'revenue_ps': ('CNY/share',
                'CNY/share',
                'latest_visible_report_cumulative',
                'Supplier cumulative operating revenue per ending share.',
                'indicator-ratio-scale-crosschecks.json'),
 'roa': ('percent',
         'ratio',
         'latest_visible_report_cumulative',
         'supplier report cumulative: EBIT / year-start and ending average total assets',
         'indicator-ratio-scale-crosschecks.json'),
 'roa2_yearly': ('percent',
                 'ratio',
                 'latest_visible_report_annualized',
                 'supplier report annualized: annualized EBIT / average total assets; not TTM',
                 'indicator-ratio-scale-crosschecks.json'),
 'roa_dp': ('percent',
            'ratio',
            'latest_visible_report_cumulative',
            'supplier report cumulative: parent net profit / year-start and ending average total '
            'assets',
            'indicator-ratio-scale-crosschecks.json'),
 'roa_yearly': ('percent',
                'ratio',
                'latest_visible_report_annualized',
                'supplier report annualized: annualized consolidated net profit / average total '
                'assets; not TTM',
                'indicator-ratio-scale-crosschecks.json'),
 'roe_avg': ('percent',
             'ratio',
             'latest_visible_report_cumulative',
             'Supplier issuance-condition average ROE; preserve scope without inventing a '
             'universal selection formula.',
             'indicator-primary-report-crosschecks.json'),
 'roe_dt': ('percent',
            'ratio',
            'latest_visible_report_cumulative',
            'supplier report cumulative: deducted net profit / year-start and ending average '
            'parent equity',
            'indicator-ratio-scale-crosschecks.json'),
 'roe_waa': ('percent',
             'ratio',
             'latest_visible_report_cumulative',
             'Supplier weighted ROE for the cumulative report period.',
             'indicator-primary-report-crosschecks.json'),
 'roe_yearly': ('percent',
                'ratio',
                'latest_visible_report_annualized',
                'supplier report annualized: annualized parent profit / average parent equity; not '
                'TTM',
                'indicator-ratio-scale-crosschecks.json'),
 'roe_yoy': ('percent',
             'ratio',
             'latest_visible_report_yoy',
             'supplier report yoy: diluted ROE; not percentage-point change or ordinary ROE growth',
             'indicator-ratio-scale-crosschecks.json'),
 'roic': ('percent',
          'ratio',
          'latest_visible_report_cumulative',
          'supplier report cumulative: after-tax EBIT / year-start and ending average invested '
          'capital',
          'indicator-ratio-scale-crosschecks.json'),
 'roic_yearly': ('percent',
                 'ratio',
                 'latest_visible_report_annualized',
                 'supplier report annualized: annualized after-tax EBIT / average invested '
                 'capital; not TTM',
                 'indicator-ratio-scale-crosschecks.json'),
 'saleexp_to_gr': ('percent',
                   'ratio',
                   'latest_visible_report_cumulative',
                   'supplier report cumulative: selling expense / total revenue',
                   'indicator-ratio-scale-crosschecks.json'),
 'salescash_to_or': ('ratio',
                     'ratio',
                     'latest_visible_report_cumulative',
                     'Supplier cumulative sales and service cash receipts / operating revenue.',
                     'indicator-ratio-scale-crosschecks.json'),
 'surplus_rese_ps': ('CNY/share',
                     'CNY/share',
                     'latest_visible_report_end',
                     'Supplier ending surplus reserve per share.',
                     'indicator-ratio-scale-crosschecks.json'),
 'tangasset_to_intdebt': ('ratio',
                          'ratio',
                          'latest_visible_report_end',
                          'supplier report end: supplier tangible net-equity amount / '
                          'interest-bearing debt',
                          'indicator-ratio-scale-crosschecks.json'),
 'tangible_asset': ('CNY',
                    'CNY',
                    'latest_visible_report_end',
                    'supplier report end: tangible net-equity amount; not total assets less '
                    'intangible assets',
                    'indicator-ratio-scale-crosschecks.json'),
 'tangibleasset_to_debt': ('ratio',
                           'ratio',
                           'latest_visible_report_end',
                           'supplier report end: supplier tangible net-equity amount / total '
                           'liabilities',
                           'indicator-ratio-scale-crosschecks.json'),
 'tangibleasset_to_netdebt': ('ratio',
                              'ratio',
                              'latest_visible_report_end',
                              'supplier report end: supplier tangible net-equity amount / net debt',
                              'indicator-ratio-scale-crosschecks.json'),
 'tax_to_ebt': ('percent',
                'ratio',
                'latest_visible_report_cumulative',
                'supplier report cumulative: income tax / total profit',
                'indicator-ratio-scale-crosschecks.json'),
 'tbassets_to_totalassets': ('percent',
                             'ratio',
                             'latest_visible_report_end',
                             'supplier report end: supplier tangible net-equity amount / total '
                             'assets',
                             'indicator-ratio-scale-crosschecks.json'),
 'total_fa_trun': ('multiple',
                   'multiple',
                   'latest_visible_report_cumulative',
                   'supplier report cumulative: total revenue / average supplier fixed-asset '
                   'aggregate',
                   'indicator-ratio-scale-crosschecks.json'),
 'total_revenue_ps': ('CNY/share',
                      'CNY/share',
                      'latest_visible_report_cumulative',
                      'Supplier cumulative total revenue per ending share.',
                      'indicator-ratio-scale-crosschecks.json'),
 'tr_yoy': ('percent',
            'ratio',
            'latest_visible_report_yoy',
            'supplier report yoy: total revenue',
            'indicator-ratio-scale-crosschecks.json'),
 'turn_days': ('day',
               'day',
               'latest_visible_report_cumulative',
               'supplier report cumulative: inventory plus receivable turnover days; not cash '
               'conversion cycle',
               'indicator-ratio-scale-crosschecks.json'),
 'undist_profit_ps': ('CNY/share',
                      'CNY/share',
                      'latest_visible_report_end',
                      'Supplier ending undistributed profit per share.',
                      'indicator-ratio-scale-crosschecks.json'),
 'valuechange_income': ('CNY',
                        'CNY',
                        'latest_visible_report_cumulative',
                        'supplier report cumulative: value-change net income; distinct from '
                        'investment income alone',
                        'indicator-ratio-scale-crosschecks.json'),
 'working_capital': ('CNY',
                     'CNY',
                     'latest_visible_report_end',
                     'supplier report end: current assets less current liabilities',
                     'indicator-ratio-scale-crosschecks.json')}
implemented06 = {'adminexp_of_gr',
 'ar_turn',
 'arturn_days',
 'assets_to_eqt',
 'assets_turn',
 'assets_yoy',
 'basic_eps_yoy',
 'bps_yoy',
 'ca_to_assets',
 'ca_turn',
 'capital_rese_ps',
 'capitalized_to_da',
 'cash_ratio',
 'cash_to_liqdebt',
 'cash_to_liqdebt_withinterest',
 'cfps',
 'cfps_yoy',
 'cogs_of_sales',
 'current_exint',
 'currentdebt_to_debt',
 'daa',
 'debt_to_assets',
 'debt_to_eqt',
 'diluted2_eps',
 'dp_assets_to_eqt',
 'dt_eps',
 'dt_eps_yoy',
 'dt_netprofit_yoy',
 'dtprofit_to_profit',
 'ebit',
 'ebit_of_gr',
 'ebit_ps',
 'ebit_to_interest',
 'ebitda',
 'ebitda_to_debt',
 'ebt_yoy',
 'eqt_to_debt',
 'eqt_to_interestdebt',
 'eqt_to_talcapital',
 'eqt_yoy',
 'equity_yoy',
 'expense_of_sales',
 'extra_item',
 'fa_turn',
 'fcfe',
 'fcfe_ps',
 'fcff',
 'fcff_ps',
 'finaexp_of_gr',
 'fixed_assets',
 'gc_of_gr',
 'gross_margin',
 'grossprofit_margin',
 'impai_ttm',
 'int_to_talcap',
 'interestdebt',
 'interst_income',
 'inv_turn',
 'invest_capital',
 'investincome_of_ebt',
 'invturn_days',
 'longdeb_to_debt',
 'longdebt_to_workingcapital',
 'n_op_profit_of_ebt',
 'nca_to_assets',
 'netdebt',
 'netprofit_margin',
 'networking_capital',
 'non_op_profit',
 'noncurrent_exint',
 'nop_to_ebt',
 'npta',
 'ocf_to_debt',
 'ocf_to_interestdebt',
 'ocf_to_netdebt',
 'ocf_to_opincome',
 'ocf_to_or',
 'ocf_to_profit',
 'ocf_to_shortdebt',
 'ocf_yoy',
 'ocfps',
 'op_income',
 'op_of_gr',
 'op_to_debt',
 'op_to_ebt',
 'op_to_liqdebt',
 'op_yoy',
 'opincome_of_ebt',
 'or_yoy',
 'profit_dedt',
 'profit_prefin_exp',
 'profit_to_gr',
 'profit_to_op',
 'q_adminexp_to_gr',
 'q_dt_roe',
 'q_dtprofit',
 'q_dtprofit_to_profit',
 'q_eps',
 'q_exp_to_sales',
 'q_finaexp_to_gr',
 'q_gc_to_gr',
 'q_gr_qoq',
 'q_gr_yoy',
 'q_gsprofit_margin',
 'q_impair_to_gr_ttm',
 'q_investincome',
 'q_investincome_to_ebt',
 'q_netprofit_margin',
 'q_netprofit_qoq',
 'q_netprofit_yoy',
 'q_npta',
 'q_ocf_to_or',
 'q_ocf_to_sales',
 'q_op_qoq',
 'q_op_to_gr',
 'q_op_yoy',
 'q_opincome',
 'q_opincome_to_ebt',
 'q_profit_qoq',
 'q_profit_to_gr',
 'q_profit_yoy',
 'q_saleexp_to_gr',
 'q_sales_qoq',
 'q_sales_yoy',
 'q_salescash_to_or',
 'quick_ratio',
 'rd_exp',
 'retained_earnings',
 'retainedps',
 'revenue_ps',
 'roa',
 'roa2_yearly',
 'roa_dp',
 'roa_yearly',
 'roe_avg',
 'roe_dt',
 'roe_waa',
 'roe_yearly',
 'roe_yoy',
 'roic',
 'roic_yearly',
 'saleexp_to_gr',
 'salescash_to_or',
 'surplus_rese_ps',
 'tangasset_to_intdebt',
 'tangible_asset',
 'tangibleasset_to_debt',
 'tangibleasset_to_netdebt',
 'tax_to_ebt',
 'tbassets_to_totalassets',
 'total_fa_trun',
 'total_revenue_ps',
 'tr_yoy',
 'turn_days',
 'undist_profit_ps',
 'valuechange_income',
 'working_capital'}
entries = []
for field in inventory:
    if field['source_endpoint'] != 'fina_indicator':
        continue
    column = field['source_column']
    scale_checks = [item for item in ratios['summary']
                    if item['field'].split('#')[0] == column]
    period_checks = [item for item in semantics['summary'] if item['field'] == column]
    entries.append({
        'dsl_identifier': field['dsl_identifier'], 'source_column': column,
        'label': field['label'], 'research_purpose': field['group'],
        'design_note': field['note'],
        'official_definition': 'https://tushare.pro/document/2?doc_id=79',
        'coverage_evidence': {'file': 'indicator-catalog-coverage.json',
                              'key': column, 'sampled_scopes': len(coverage[column]['scope'])},
        'semantic_decision': ({
            'source_unit': decisions[column][0],
            'canonical_unit': decisions[column][1],
            'period': decisions[column][2],
            'supplier_scope': decisions[column][3],
            'evidence_file': decisions[column][4],
            'applicability': 'See per-field five-security coverage evidence; no claim of universal company-type coverage. Missing or inapplicable supplier values remain missing.',
            'qualification_status': 'unit_period_scope_recorded; serial Standards and Spec reviews passed with bounded applicability evidence',
        } if column in decisions else None),
        'scale_hypotheses': scale_checks,
        'primary_report_evidence': [x for x in primary if x['field'] == column],
        'period_and_scope_hypotheses': period_checks,
        'pilot_qualification': 'indicator-pilot-qualification.md' if column in pilot else None,
        'production_status': ('implemented_in_ticket05' if column in pilot else
                              'implemented_in_ticket06'
                              if column in implemented06 else 'not_registered'),
        'remaining_review': [],
    })
assert len(entries) == 163
result = {'scope': 'evidence index, not a production registry or proof all fields are qualified',
          'total': len(entries), 'fields': entries}
(root / 'indicator-field-qualification-ledger.json').write_text(
    json.dumps(result, ensure_ascii=False, indent=2) + '\n')
print({'total': len(entries), 'pilot': len(pilot),
       'with_scale_hypotheses': sum(bool(x['scale_hypotheses']) for x in entries),
       'with_period_hypotheses': sum(bool(x['period_and_scope_hypotheses']) for x in entries)})
