#!/usr/bin/env python3
from __future__ import annotations

import os

import boto3
from botocore.config import Config


def main() -> None:
    endpoint_url = os.environ["THESISTRACE_S3_ENDPOINT_URL"]
    client = boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=os.environ["THESISTRACE_S3_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["THESISTRACE_S3_SECRET_ACCESS_KEY"],
        region_name="us-east-1",
        config=Config(
            connect_timeout=1,
            read_timeout=1,
            retries={"max_attempts": 0, "mode": "standard"},
        ),
    )
    try:
        client.list_buckets()
    finally:
        client.close()


if __name__ == "__main__":
    main()
