// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bQVQPOOOhQPO'#C`O!SQPO'#CbOVQPO'#CeOOQO'#Cg'#CgOVQPO'#CfQ!XQPOOOOQO'#C^'#C^O!gQPO,58|O!nQPO,59POOQO,59Q,59QOOQO'#Ci'#CiOOQO'#Cj'#CjOVQPO,59SOVQPO,59SO#PQPO'#CdOOQO1G.h1G.hO#eQPO1G.hOOQO1G.k1G.kOOQO1G.n1G.nO#jQPO1G.nOVQPO'#CkO$RQPO,59OOOQO7+$S7+$SO$ZQPO,59VOOQO-E6i-E6i",
  stateData: "$o~ObOS~ORVOTPOcROfSOgSO~O`SXcVXfSXgSXhSXiSXeSXdSX~OcWO~Of[Og[OhZOiZO~Oe`O~PVOebOf[Og[OhZOiZO~OdeOf[Og[OhZOiZOeWX~OegO~OhZOiZO`[if[ig[ie[id[i~OdeOeWa~Of[Og[OhZOiZOd_ae_a~O",
  goto: "!y`PPaPvPv!P!Yvv!]v!f!m!sQUOQXRQYTQ_WQc]Qd^Rhe_VORTW]^e_QORTW]^eRaW_TORTW]^eZ]UX_dhX^UX_hQf_Rif",
  nodeNames: "⚠ Formula Expression Number FieldName Identifier CallExpression FunctionName ArgumentList ParenthesizedExpression UnaryExpression UnaryOperator BinaryExpression MultiplyOperator AddOperator",
  maxTerm: 25,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "$u~RdX^!apq!axy#Uyz#Zz{#`{|#e|}#j}!O#o!P!Q#t!Q![#y!c!}$d#T#o$d#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~!fYb~X^!apq!a#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~#ZOc~~#`Oe~~#eOh~~#jOf~~#oOd~~#tOg~~#yOi~~$OQR~!O!P$U!Q![#y~$XP!Q![$[~$aPR~!Q![$[~$iST~!Q![$d!c!}$d#R#S$d#T#o$d",
  tokenizers: [0],
  topRules: {"Formula":[0,1]},
  tokenPrec: 0
})
