// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,not:56, and:76, or:78}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%|QVQPOOOhQPO'#C`O!lQPO'#CbOVQPO'#CeOOQO'#Cg'#CgOVQPO'#CfOOQO'#Ci'#CiOVQPO'#ChQ!qQPOOOOQO'#C^'#C^O#iQPO,58|O#pQPO,59POOQO,59Q,59QO$iQPO,59SOOQO'#Ck'#CkOOQO'#Cl'#ClOOQO'#Cm'#CmOOQO'#Cn'#CnOOQO'#Co'#CoOVQPO,59UOVQPO,59UOVQPO,59UOVQPO,59UOVQPO,59UO$|QPO'#CdOOQO1G.h1G.hO%WQPO1G.hOOQO1G.k1G.kOOQO1G.p1G.pO&WQPO1G.pO&bQPO1G.pO&lQPO1G.pO'PQPO1G.pOVQPO'#CpO'dQPO,59OOOQO7+$S7+$SO'lQPO,59[OOQO-E6n-E6n",
  stateData: "'v~OgOS~ORXOTPOhROkSOlUO~OeSXhVXkSXmSXnSXoSXpSXqSXrSXsSXtSXuSXvSXwSXjSXiSX~OhYO~Ok_Om^On^Oo_Op`Oq`Or`Os`Ot`Ou`OvaOwbO~OjiO~PVOjkO~P!qOk_Om^On^Oo_Op`Oq`Or`Os`Ot`Ou`O~Oe[av[aw[aj[ai[a~P#wOiqOjWX~P!qOjsO~Om^On^Oe^ip^iq^ir^is^it^iu^iv^iw^ij^ii^i~Ok^io^i~P%]Ok_Oo_O~P%]Oe^iv^iw^ij^ii^i~P#wOvaOe^iw^ij^ii^i~P#wOiqOjWa~Oidajda~P!qO",
  goto: "$eePPfP!XP!X!f!s!X!X!v!X#T!X#b#m#w$Q$X$_QWOQZRQ[TQ]VQhYQlcQmdQneQofQpgRtqgXORTVYcdefgqgQORTVYcdefgqRjYgTORTVYcdefgqgVORTVYcdefgqccWZ]hmnoptadWZ]hnopt_eWZ]hoptZfWZhptXgWZhtQrhRur",
  nodeNames: "⚠ Formula Expression Number FieldName Identifier CallExpression FunctionName ArgumentList ParenthesizedExpression UnaryExpression UnaryOperator NotExpression NotOperator BinaryExpression MultiplyOperator AddOperator ComparisonOperator AndOperator OrOperator",
  maxTerm: 39,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&T~RhX^!mpq!mqr#bxy#myz#rz{#w{|#||}$R}!O$W!P!Q$]!Q![$b!^!_${!_!`%Y!`!a%e!c!}%r#T#o%r#y#z!m$f$g!m#BY#BZ!m$IS$I_!m$I|$JO!m$JT$JU!m$KV$KW!m&FU&FV!m~!rYg~X^!mpq!m#y#z!m$f$g!m#BY#BZ!m$IS$I_!m$I|$JO!m$JT$JU!m$KV$KW!m&FU&FV!m~#eP!_!`#h~#mOu~~#rOh~~#wOj~~#|Om~~$ROo~~$WOi~~$]Ok~~$bOn~~$gQR~!O!P$m!Q![$b~$pP!Q![$s~$xPR~!Q![$s~%QPr~!_!`%T~%YOs~~%]P!_!`%`~%eOt~~%jPp~!_!`%m~%rOq~~%wST~!Q![%r!c!}%r#R#S%r#T#o%r",
  tokenizers: [0],
  topRules: {"Formula":[0,1]},
  specialized: [{term: 5, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
